name = tennis Bundy Two Column Responsive Layout
description = A 12 column Singularity GS layout with a header, titlebar, two-column content region, 3 column footer prefix and 2 column footer.
preview = preview.png
template = tennis-bundy-twocol-layout

; Regions
regions[banner]         	= Banner
regions[branding]       	= Branding
regions[help]           	= Help
regions[titlebox]        	= Title Box
regions[content]        	= Content
regions[sidebar_first]  	= First sidebar
regions[footer_first]       = Footer First
regions[footer_second]      = Footer Second
regions[footer_strapline]   = Footer Strapline

; Stylesheets
stylesheets[all][] = css/layouts/tennis-bundy-twocol/tennis-bundy-twocol-layout.css
stylesheets[all][] = css/layouts/tennis-bundy-twocol/tennis-bundy-twocol-layout.no-query.css