name = tennis Mercury Two Column Responsive Layout
description = A 12 column Singularity GS layout with a header, titlebar, two-column content region, 3 column footer prefix and 2 column footer.
preview = preview.png
template = tennis-mercury-twocol-layout

; Regions
regions[nav]     = Navigation bar
regions[banner]         = Banner
regions[branding]       = Branding
regions[content_header]    = Content Header
regions[titlebox]    	= Title Box
regions[titlebox_right]    	= Title Box Right
regions[help]           = Help
regions[content]        = Content
regions[content_footer]        = Content Footer
regions[sidebar_first]  = First sidebar
regions[suffix_first]   = Suffix First
regions[suffix_second]  = Suffix Second
regions[suffix_third]   = Suffix Third
regions[footer_first]          = Footer First
regions[footer_second]         = Footer Second
regions[footer_strapline]         = Footer Strapline

; Stylesheets
stylesheets[all][] = css/layouts/tennis-mercury-twocol/tennis-mercury-twocol-layout.css
stylesheets[all][] = css/layouts/tennis-mercury-twocol/tennis-mercury-twocol-layout.no-query.css